### ISSUE TITLE
Problem with route

### ISSUE THREAD

**Issue by brunopiaui** [muthu-kc/instagram-private-api-laravel#1]
Hi,

There is no "alogin" route as it is in the documentation.

Are there any fixes I can do to resolve this issue?

Thanks!!

**Comment by muthu-kc** [comment]
Please download as zip and try it. It's not composer supported. I have some changes inside Vendor.

**Comment by muthu-kc** [comment]
@brunopiaui Moved routes to web/routes file. You can see routes there now for admin login /alogin.
