### ISSUE TITLE
Get Likers for Media Post

### ISSUE THREAD

**Issue by Flow999Cloud** [muthu-kc/instagram-private-api-laravel#3]
Hi, @muthu-kc 

Do you know how to get likers for certain media post using @liamcottle's private api?

Thanks.

**Comment by muthu-kc** [comment]
$instagram_instance->getMediaLikes($media_id);

**Comment by Flow999Cloud** [comment]
Wow, dope.
Thanks for your quick response. @muthu-kc.
I appreciate it.  :pray:

When I tried to call that functionality, I get following error message.
```
"message": "Call to undefined method Instagram\\Instagram::getMediaLikes()",
```

So I tried to find it in the private api repository(in vendor folder).
It seems like there is no `getMediaLikes($media_id)` function in the repository.
Could you let me know what is the issue on my side?

Thanks.

**Comment by Flow999Cloud** [comment]
Hi, @muthu-kc 

I've created a new API to get the likers for media posts and made a [PR](https://github.com/liamcottle/Instagram-SDK-PHP/pull/58) to the @liamcottle's repository.

Thanks for your time on this issue.

**Comment by muthu-kc** [comment]
Great.
